In [38]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as pyplot
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
print("Libraries imported successfully!!!")

Libraries imported successfully!!!

In [39]:
df = pd.read_csv("../Data/online_shoppers_intention.csv") #Load the dataset
df.head(10) #Display first 10 rows

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
0,0,0.0,0,0.0,1,0.000000,0.200000,0.200000,0.0,0.0,Feb,1,1,1,1,Returning_Visitor,False,False
1,0,0.0,0,0.0,2,64.000000,0.000000,0.100000,0.0,0.0,Feb,2,2,1,2,Returning_Visitor,False,False
2,0,0.0,0,0.0,1,0.000000,0.200000,0.200000,0.0,0.0,Feb,4,1,9,3,Returning_Visitor,False,False
3,0,0.0,0,0.0,2,2.666667,0.050000,0.140000,0.0,0.0,Feb,3,2,2,4,Returning_Visitor,False,False
4,0,0.0,0,0.0,10,627.500000,0.020000,0.050000,0.0,0.0,Feb,3,3,1,4,Returning_Visitor,True,False
5,0,0.0,0,0.0,19,154.216667,0.015789,0.024561,0.0,0.0,Feb,2,2,1,3,Returning_Visitor,False,False
6,0,0.0,0,0.0,1,0.000000,0.200000,0.200000,0.0,0.4,Feb,2,4,3,3,Returning_Visitor,False,False
7,1,0.0,0,0.0,0,0.000000,0.200000,0.200000,0.0,0.0,Feb,1,2,1,5,Returning_Visitor,True,False
8,0,0.0,0,0.0,2,37.000000,0.000000,0.100000,0.0,0.8,Feb,2,2,2,3,Returning_Visitor,False,False
9,0,0.0,0,0.0,3,738.000000,0.000000,0.022222,0.0,0.4,Feb,2,4,1,2,Returning_Visitor,False,False

In [40]:
df.info() #Shows summary of the dataset

df.isna().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12330 entries, 0 to 12329
Data columns (total 18 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Administrative           12330 non-null  int64
 1   Administrative_Duration  12330 non-null  float64
 2   Informational            12330 non-null  int64
 3   Informational_Duration   12330 non-null  float64
 4   ProductRelated           12330 non-null  int64
 5   ProductRelated_Duration  12330 non-null  float64
 6   BounceRates              12330 non-null  float64
 7   ExitRates                12330 non-null  float64
 8   PageValues               12330 non-null  float64
 9   SpecialDay               12330 non-null  float64
 10  Month                    12330 non-null  object
 11  OperatingSystems         12330 non-null  int64
 12  Browser                  12330 non-null  int64
 13  Region                   12330 non-null  int64
 14  TrafficType              12330 non-null  int64
 15  VisitorType              12330 non-null  object
 16  Weekend                  12330 non-null  bool
 17  Revenue                  12330 non-null  bool
dtypes: bool(2), float64(7), int64(7), object(2)
memory usage: 1.5+ MB

Administrative             0
Administrative_Duration    0
Informational              0
Informational_Duration     0
ProductRelated             0
ProductRelated_Duration    0
BounceRates                0
ExitRates                  0
PageValues                 0
SpecialDay                 0
Month                      0
OperatingSystems           0
Browser                    0
Region                     0
TrafficType                0
VisitorType                0
Weekend                    0
Revenue                    0
dtype: int64

In [41]:
df.describe() #Shows stats of the dataset

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,OperatingSystems,Browser,Region,TrafficType
count,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000
mean,2.315166,80.818611,0.503569,34.472398,31.731468,1194.746220,0.022191,0.043073,5.889258,0.061427,2.124006,2.357097,3.147364,4.069586
std,3.321784,176.779107,1.270156,140.749294,44.475503,1913.669288,0.048488,0.048597,18.568437,0.198917,0.911325,1.717277,2.401591,4.025169
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000
25%,0.000000,0.000000,0.000000,0.000000,7.000000,184.137500,0.000000,0.014286,0.000000,0.000000,2.000000,2.000000,1.000000,2.000000
50%,1.000000,7.500000,0.000000,0.000000,18.000000,598.936905,0.003112,0.025156,0.000000,0.000000,2.000000,2.000000,3.000000,2.000000
75%,4.000000,93.256250,0.000000,0.000000,38.000000,1464.157214,0.016813,0.050000,0.000000,0.000000,3.000000,2.000000,4.000000,4.000000
max,27.000000,3398.750000,24.000000,2549.375000,705.000000,63973.522230,0.200000,0.200000,361.763742,1.000000,8.000000,13.000000,9.000000,20.000000

In [42]:
df["Revenue"].mean() #To calculate the mean of the revenue

np.float64(0.15474452554744525)

In [43]:
'''
To calculate the total count with normalized values,
we found that total count is 100% with false value of 84.5% and true value of 15.5%
This means that only 15.5% of the users have revenue only.

'''
df["Revenue"].value_counts(normalize = True)

Revenue
False    0.845255
True     0.154745
Name: proportion, dtype: float64

In [44]:
#Month is ordered logically
month_order = ["Feb", "Mar", "May", "June", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
df["Month"] = pd.Categorical(df["Month"], categories=month_order, ordered=True)

month_rev = df.groupby("Month")["Revenue"].mean().sort_index()
month_counts = df["Month"].value_counts().loc[month_order]

month_rev, month_counts

(Month
 Feb     0.016304
 Mar     0.100682
 May     0.108502
 June    0.100694
 Jul     0.152778
 Aug     0.175520
 Sep     0.191964
 Oct     0.209472
 Nov     0.253502
 Dec     0.125072
 Name: Revenue, dtype: float64,
 Month
 Feb      184
 Mar     1907
 May     3364
 June     288
 Jul      432
 Aug      433
 Sep      448
 Oct      549
 Nov     2998
 Dec     1727
 Name: count, dtype: int64)

In [45]:
import plotly.express as px
#Shows the average purchase rate by month
fig = px.bar(month_rev.reset_index(), x="Month", y="Revenue",
             title="Average purchase rate by month")
fig.show()

Conversion rates are lower in the feb, june and july as compared to the other months. Most traffic is generated in the month of may and november, so these months are high conversion months which are importnant for analysing and modelling purchase intention.

In [46]:
#Shows the average purchase rate by visitor type and weekend
visitor_rev = df.groupby("VisitorType")["Revenue"].mean().sort_values(ascending=False)
weekend_rev = df.groupby("Weekend")["Revenue"].mean()

visitor_counts = df["VisitorType"].value_counts()
weekend_counts = df["Weekend"].value_counts()

visitor_rev, visitor_counts, weekend_rev, weekend_counts

(VisitorType
 New_Visitor          0.249115
 Other                0.188235
 Returning_Visitor    0.139323
 Name: Revenue, dtype: float64,
 VisitorType
 Returning_Visitor    10551
 New_Visitor           1694
 Other                   85
 Name: count, dtype: int64,
 Weekend
 False    0.148911
 True     0.173989
 Name: Revenue, dtype: float64,
 Weekend
 False    9462
 True     2868
 Name: count, dtype: int64)

In [47]:
#This 
vt_week = df.groupby(["VisitorType", "Weekend"])["Revenue"].mean().unstack() #unstack used to make the weekend column as columns
vt_week

Weekend               False     True
VisitorType
New_Visitor        0.260905  0.219207
Other              0.192308  0.142857
Returning_Visitor  0.131840  0.164987

New visitors has the highest conversion rate on weekdays while returning visitors has the highest conversion rate on weekends as compared to the weekdays.

In [58]:
df["Revenue"] = df["Revenue"].astype(int)  # cast True/False to 1/0

int_cat = ["OperatingSystems", "Browser", "Region", "TrafficType", "Weekend"]
for col in int_cat:
    df[col] = df[col].astype("category")
df.info()
numeric_cols = df.select_dtypes(include="number").columns
corr = df[numeric_cols].corr()["Revenue"].sort_values(ascending=False)
corr

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12330 entries, 0 to 12329
Data columns (total 18 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Administrative           12330 non-null  int64
 1   Administrative_Duration  12330 non-null  float64
 2   Informational            12330 non-null  int64
 3   Informational_Duration   12330 non-null  float64
 4   ProductRelated           12330 non-null  int64
 5   ProductRelated_Duration  12330 non-null  float64
 6   BounceRates              12330 non-null  float64
 7   ExitRates                12330 non-null  float64
 8   PageValues               12330 non-null  float64
 9   SpecialDay               12330 non-null  float64
 10  Month                    12330 non-null  category
 11  OperatingSystems         12330 non-null  category
 12  Browser                  12330 non-null  category
 13  Region                   12330 non-null  category
 14  TrafficType              12330 non-null  category
 15  VisitorType              12330 non-null  object
 16  Weekend                  12330 non-null  category
 17  Revenue                  12330 non-null  int64
dtypes: category(6), float64(7), int64(4), object(1)
memory usage: 1.2+ MB

Revenue                    1.000000
PageValues                 0.492569
ProductRelated             0.158538
ProductRelated_Duration    0.152373
Administrative             0.138917
Informational              0.095200
Administrative_Duration    0.093587
Informational_Duration     0.070345
SpecialDay                -0.082305
BounceRates               -0.150673
ExitRates                 -0.207071
Name: Revenue, dtype: float64

In [49]:
corr_top = corr.drop("Revenue").sort_values(ascending=False)
corr_top

PageValues                 0.492569
ProductRelated             0.158538
ProductRelated_Duration    0.152373
Administrative             0.138917
Informational              0.095200
Administrative_Duration    0.093587
Informational_Duration     0.070345
Browser                    0.023984
TrafficType               -0.005113
Region                    -0.011595
OperatingSystems          -0.014668
SpecialDay                -0.082305
BounceRates               -0.150673
ExitRates                 -0.207071
Name: Revenue, dtype: float64

Session with higher page value are most likely to be converted and high bounce rates and exit rates are with fewer conversions likely negatively correlated with conversion rate.

In [60]:
cat_cols = df.select_dtypes(include=["object", "category", "bool"]).columns
num_cols = df.select_dtypes(include=["int64", "float64"]).columns

print("Categorical columns =", cat_cols)
print("Numerical columns =", num_cols)

Categorical columns = Index(['Month', 'OperatingSystems', 'Browser', 'Region', 'TrafficType',
       'VisitorType', 'Weekend'],
      dtype='object')
Numerical columns = Index(['Administrative', 'Administrative_Duration', 'Informational',
       'Informational_Duration', 'ProductRelated', 'ProductRelated_Duration',
       'BounceRates', 'ExitRates', 'PageValues', 'SpecialDay', 'Revenue'],
      dtype='object')

In [62]:
Y = df["Revenue"]
X = df.drop("Revenue", axis = 1)

In [67]:
cat_cols = X.select_dtypes(include = ["object", "category", "bool"]).columns
X_encoded = pd.get_dummies(X, columns = cat_cols, drop_first = True)
print(X_encoded.head())
print(X_encoded.shape)

   Administrative  Administrative_Duration  Informational  \
0               0                      0.0              0
1               0                      0.0              0
2               0                      0.0              0
3               0                      0.0              0
4               0                      0.0              0

   Informational_Duration  ProductRelated  ProductRelated_Duration  \
0                     0.0               1                 0.000000
1                     0.0               2                64.000000
2                     0.0               1                 0.000000
3                     0.0               2                 2.666667
4                     0.0              10               627.500000

   BounceRates  ExitRates  PageValues  SpecialDay  ...  TrafficType_14  \
0         0.20       0.20         0.0         0.0  ...           False
1         0.00       0.10         0.0         0.0  ...           False
2         0.20       0.20         0.0         0.0  ...           False
3         0.05       0.14         0.0         0.0  ...           False
4         0.02       0.05         0.0         0.0  ...           False

   TrafficType_15  TrafficType_16  TrafficType_17  TrafficType_18  \
0           False           False           False           False
1           False           False           False           False
2           False           False           False           False
3           False           False           False           False
4           False           False           False           False

   TrafficType_19  TrafficType_20  VisitorType_Other  \
0           False           False              False
1           False           False              False
2           False           False              False
3           False           False              False
4           False           False              False

   VisitorType_Returning_Visitor  Weekend_True
0                           True         False
1                           True         False
2                           True         False
3                           True         False
4                           True          True

[5 rows x 68 columns]
(12330, 68)

In [69]:
df_model = X_encoded.copy()
df_model["Revenue"] = Y
df_model.head()

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,...,TrafficType_15,TrafficType_16,TrafficType_17,TrafficType_18,TrafficType_19,TrafficType_20,VisitorType_Other,VisitorType_Returning_Visitor,Weekend_True,Revenue
0,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,...,False,False,False,False,False,False,False,True,False,0
1,0,0.0,0,0.0,2,64.000000,0.00,0.10,0.0,0.0,...,False,False,False,False,False,False,False,True,False,0
2,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,...,False,False,False,False,False,False,False,True,False,0
3,0,0.0,0,0.0,2,2.666667,0.05,0.14,0.0,0.0,...,False,False,False,False,False,False,False,True,False,0
4,0,0.0,0,0.0,10,627.500000,0.02,0.05,0.0,0.0,...,False,False,False,False,False,False,False,True,True,0

In [70]:
df_model.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12330 entries, 0 to 12329
Data columns (total 69 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Administrative                 12330 non-null  int64
 1   Administrative_Duration        12330 non-null  float64
 2   Informational                  12330 non-null  int64
 3   Informational_Duration         12330 non-null  float64
 4   ProductRelated                 12330 non-null  int64
 5   ProductRelated_Duration        12330 non-null  float64
 6   BounceRates                    12330 non-null  float64
 7   ExitRates                      12330 non-null  float64
 8   PageValues                     12330 non-null  float64
 9   SpecialDay                     12330 non-null  float64
 10  Month_Mar                      12330 non-null  bool
 11  Month_May                      12330 non-null  bool
 12  Month_June                     12330 non-null  bool
 13  Month_Jul                      12330 non-null  bool
 14  Month_Aug                      12330 non-null  bool
 15  Month_Sep                      12330 non-null  bool
 16  Month_Oct                      12330 non-null  bool
 17  Month_Nov                      12330 non-null  bool
 18  Month_Dec                      12330 non-null  bool
 19  OperatingSystems_2             12330 non-null  bool
 20  OperatingSystems_3             12330 non-null  bool
 21  OperatingSystems_4             12330 non-null  bool
 22  OperatingSystems_5             12330 non-null  bool
 23  OperatingSystems_6             12330 non-null  bool
 24  OperatingSystems_7             12330 non-null  bool
 25  OperatingSystems_8             12330 non-null  bool
 26  Browser_2                      12330 non-null  bool
 27  Browser_3                      12330 non-null  bool
 28  Browser_4                      12330 non-null  bool
 29  Browser_5                      12330 non-null  bool
 30  Browser_6                      12330 non-null  bool
 31  Browser_7                      12330 non-null  bool
 32  Browser_8                      12330 non-null  bool
 33  Browser_9                      12330 non-null  bool
 34  Browser_10                     12330 non-null  bool
 35  Browser_11                     12330 non-null  bool
 36  Browser_12                     12330 non-null  bool
 37  Browser_13                     12330 non-null  bool
 38  Region_2                       12330 non-null  bool
 39  Region_3                       12330 non-null  bool
 40  Region_4                       12330 non-null  bool
 41  Region_5                       12330 non-null  bool
 42  Region_6                       12330 non-null  bool
 43  Region_7                       12330 non-null  bool
 44  Region_8                       12330 non-null  bool
 45  Region_9                       12330 non-null  bool
 46  TrafficType_2                  12330 non-null  bool
 47  TrafficType_3                  12330 non-null  bool
 48  TrafficType_4                  12330 non-null  bool
 49  TrafficType_5                  12330 non-null  bool
 50  TrafficType_6                  12330 non-null  bool
 51  TrafficType_7                  12330 non-null  bool
 52  TrafficType_8                  12330 non-null  bool
 53  TrafficType_9                  12330 non-null  bool
 54  TrafficType_10                 12330 non-null  bool
 55  TrafficType_11                 12330 non-null  bool
 56  TrafficType_12                 12330 non-null  bool
 57  TrafficType_13                 12330 non-null  bool
 58  TrafficType_14                 12330 non-null  bool
 59  TrafficType_15                 12330 non-null  bool
 60  TrafficType_16                 12330 non-null  bool
 61  TrafficType_17                 12330 non-null  bool
 62  TrafficType_18                 12330 non-null  bool
 63  TrafficType_19                 12330 non-null  bool
 64  TrafficType_20                 12330 non-null  bool
 65  VisitorType_Other              12330 non-null  bool
 66  VisitorType_Returning_Visitor  12330 non-null  bool
 67  Weekend_True                   12330 non-null  bool
 68  Revenue                        12330 non-null  int64
dtypes: bool(58), float64(7), int64(4)
memory usage: 1.7 MB